name = "echo-arena-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

# Environment variables
[vars]
ENVIRONMENT = "development"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "echo-arena-db"
database_id = "placeholder-will-be-set-on-first-deploy"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "placeholder-cache-kv-id"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder-rate-limit-kv-id"

[[kv_namespaces]]
binding = "RESULTS"
id = "placeholder-results-kv-id"

# Durable Objects
[[durable_objects.bindings]]
name = "MATCH_COORDINATOR"
class_name = "MatchCoordinator"
script_name = "echo-arena-worker"

[[migrations]]
tag = "v1"
new_classes = ["MatchCoordinator"]

# Durable Object class definition
[durable_objects]
bindings = [
  { name = "MATCH_COORDINATOR", class_name = "MatchCoordinator" }
]

# Build configuration
[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "echo-arena-db-prod"
database_id = "production-database-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "production-cache-kv-id"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "production-rate-limit-kv-id"

[[env.production.kv_namespaces]]
binding = "RESULTS"
id = "production-results-kv-id"
