name = "echo-arena-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "development"
BSC_RPC_URL = "https://bsc-dataseed.binance.org"
ECHO_TOKEN_ADDRESS = "0x0000000000000000000000000000000000000000"
FREE_START = "2025-10-24T00:00:00Z"
FREE_END = "2025-10-31T23:59:59Z"
ALLOWLIST_ADMINS = "0x3587e9fe0a1e0ba8a3c6bcfb0d7d5870c08b2c1d"
BITQUERY_API_TOKEN = "ory_at_d4wXS3eCmZdFeyPOQca8NjFqEkUvfpHaKTbUh3wQBVA.RDyBVU6dWD7hb7tR1uzg6dWDVUXTm6V9hjT6vU2Boaw"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "echo-arena-db"
database_id = "3054a7d7-e2c1-4a40-be4f-0eacd23a8ef0"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "e43d9e9674f24ac0afdddf7219c5b57c"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c1ad15e94b3a4566bef6f9ca9a8d03ce"

[[kv_namespaces]]
binding = "RESULTS"
id = "d29119c1e6b94f80999f2e228cd6517c"

# Durable Objects
[[durable_objects.bindings]]
name = "MATCH_COORDINATOR"
class_name = "MatchCoordinator"

[[migrations]]
tag = "v1"
new_classes = ["MatchCoordinator"]

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "echo-arena-db"
database_id = "3054a7d7-e2c1-4a40-be4f-0eacd23a8ef0"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "e43d9e9674f24ac0afdddf7219c5b57c"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "c1ad15e94b3a4566bef6f9ca9a8d03ce"

[[env.production.kv_namespaces]]
binding = "RESULTS"
id = "d29119c1e6b94f80999f2e228cd6517c"
